## HCIA-AI CERTIFICATION DAILY EXERCISE: PYTHON BASICS

### 1. Check the version of pandas and numpy installed

In [1]:
import numpy; 
print (numpy.version.version) #numpy version


1.24.3


In [7]:
import pandas as pd;
print (pd.__version__) #pandas version

2.0.3


 ### 2.Write a program to print 'Hello HCIA PDTP-Huawei Team

In [2]:
print("Hello HCIA PDTP-Huawei Team")

Hello HCIA PDTP-Huawei Team


### 3. Write a program to define two variables, calculate their sum and display the results

In [ ]:
x= 9
y= 7
print(x+y)

16


### 4. a) Write a program to define a tuple that contains only one element

In [ ]:
thistuple = ("apple",)
print(type(thistuple))

### 4. b) Write a program to define a tuple and then use the 'for loop' to print all the elements.

In [18]:
thistuple = ("apple", "banana", "cherry")
# print(thistuple)
for i in thistuple:
    print(i)
# for i in range(len(thistuple)):
#     print(thistuple[i])

apple
banana
cherry


#### 5) Write code to create a Python dictionary (the dict type) and print out the details. Add two entries to the dictionary: Associate the key ‘name’ with the value ‘Reagan’, and associate the key ‘phone’ with ‘+254 722 222333’

In [11]:
mydict ={
    "name": "Reagan",
    "phone" :  "+254 722 222333"
}
print(mydict)

{'name': 'Reagan', 'phone': '+254 722 222333'}


### 6. a) Define a function to do Multiplication, such as Mul(8,6),and it output 42.

In [11]:
def Mul(a,b):
    return a*b
print(Mul(2,5))

10


### b) Complete the function definition so it returns the square of the product of the parameters,so sqrProd(2, 5) returns (2* 5) * (2* 5) = 100. def sqrProd(x, y)

In [12]:
def sqrProd(a,b):
    return (a*b)*(a*b)
print(sqrProd(2,5))

100


### 7.a) Use numpy to define an array, the shape of it is (5,5) and all elements of it is 0.

In [17]:
import numpy as np
myArray = np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
print(np.array(myArray).shape)
print(myArray)

    

(5, 5)
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### 7. b) Create a 3x3 matrix with values ranging from 0 to 8

In [1]:
import numpy as np
matrix = np.arange(12).reshape(3,4)
print(matrix)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### 7. c.) Find indices of non-zero elements from [1,2,0,0,4,0]


In [22]:
import numpy as np
myArray = np.array([1,2,0,0,4,0])
print(np.nonzero(myArray))

(array([0, 1, 4], dtype=int64),)


### 7. d) Create a 10x10 array with random values and find the minimum and maximum values

In [24]:
import numpy as np
arr = np.random.rand(10, 10)
print(arr)
min_val = np.min(arr)
max_val = np.max(arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)


[[0.71694302 0.42769954 0.44524009 0.04962637 0.71166453 0.94851609
  0.72389172 0.30173287 0.71041749 0.97280405]
 [0.27414638 0.29777229 0.02079225 0.85627847 0.78724584 0.80790829
  0.43446209 0.87688191 0.67110773 0.86896838]
 [0.14441858 0.06196245 0.04053999 0.61610389 0.99553872 0.79583024
  0.37585578 0.85112787 0.22924671 0.46543461]
 [0.23527361 0.98833493 0.2474714  0.71157973 0.62331282 0.25834898
  0.35249545 0.65258901 0.55016463 0.82406548]
 [0.80484186 0.79650277 0.93254747 0.54169951 0.49414001 0.56874559
  0.10453492 0.76832635 0.48470812 0.00775843]
 [0.04741304 0.06024787 0.0288332  0.89627449 0.4745718  0.50109488
  0.06653119 0.80938339 0.2592455  0.91372838]
 [0.18998975 0.9937286  0.09448019 0.71908582 0.35911328 0.18953255
  0.34160676 0.00988359 0.0952551  0.61707892]
 [0.77995732 0.76445937 0.57103459 0.28576302 0.86300445 0.81070688
  0.5916738  0.60729637 0.66566461 0.97961283]
 [0.90341887 0.63902565 0.2248493  0.55878289 0.77397458 0.89201966
  0.06573459

### 7.e) Create a random vector of size 30 and find the mean value

In [29]:
import numpy as np
vector = np.random.rand(30)
print(vector)
x = np.mean(vector)
print(f"The mean is {x}")

[0.68376153 0.10067012 0.91999099 0.68070229 0.28243537 0.07531334
 0.77691633 0.73959353 0.43678636 0.55083258 0.37973103 0.10795663
 0.47454883 0.89832521 0.97013501 0.01719915 0.63986177 0.90813407
 0.09247885 0.72901748 0.53979671 0.40573814 0.0544674  0.08729247
 0.46830984 0.32478964 0.17687037 0.29285526 0.28233767 0.09799364]
The mean is 0.4398280530248962


### 8) Write a Python program that prompts the user for two numbers, reads them in, and prints out the product, labeled appropriately.


In [1]:
import numpy as np
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
product = num1 * num2
print("The product of", num1, "and", num2, "is", product)


The product of 5.0 and 6.0 is 30.0


### 9) Complete the code for the following function so it matches its documentation:def doubleList(numberList):For each of the numbers in the list numberList, print a line containing twice the original number. For example,doubleList ([3, 1, 5]) would print 6, 2, 10

In [3]:
def doubleList(numberList):
    for num in numberList:
        print(num * 2)
doubleList ([3, 1, 5]) 

6
2
10
